# Generated by Django 2.0.4 on 2018-04-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survived', models.IntegerField()),
                ('ticket_class', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField()),
                ('age', models.IntegerField()),
                ('siblings_to_spouses', models.IntegerField()),
                ('parents_to_children', models.IntegerField()),
                ('ticket_number', models.IntegerField()),
                ('fare', models.IntegerField()),
                ('cabin_number', models.CharField(max_length=4, null=True)),
                ('embarked_from', models.IntegerField()),
            ],
        ),
    ]
