# Generated by Django 2.0.4 on 2018-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='cabin_number',
            new_name='cabin',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='name',
            new_name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='ticket_number',
        ),
        migrations.AddField(
            model_name='passenger',
            name='ticket',
            field=models.CharField(default='none', max_length=12),
        ),
    ]
