# Generated by Django 2.0.4 on 2018-04-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0002_auto_20180423_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='fare',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='parents_to_children',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='siblings_to_spouses',
            field=models.IntegerField(blank=True),
        ),
    ]
