# Generated by Django 2.0.4 on 2018-04-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictor', '0003_auto_20180423_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='cabin',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='embarked_from',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='fare',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='parents_to_children',
            field=models.IntegerField(default=42),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='siblings_to_spouses',
            field=models.IntegerField(default=42),
        ),
    ]
